# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludlow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='local_path',
        ),
        migrations.AddField(
            model_name='course',
            name='rel_path',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
