# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludlow', '0002_auto_20170317_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='rel_path',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
