# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludlow', '0003_auto_20170318_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
